import { AgentConfig } from '@/domain/services/ai/Agent';

const agentsDB: Record<string, AgentConfig> = {
  'PDFImportAgent': {
    name: 'PDFImportAgent',
    description: 'Processes input files, extracting pages and layouts.',
    capabilities: ['pdf-page-extraction', 'layout-analysis'],
    supportedModels: ['gpt-4o', 'mock-gpt-4'],
    preferredModel: 'gpt-4o',
    promptId: 'ocr-extract',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 3, initialDelayMs: 1000, backoffMultiplier: 2 },
  },
  'OCRValidationAgent': {
    name: 'OCRValidationAgent',
    description: 'Validates confidence scores of OCR texts and tags uncertain fields.',
    capabilities: ['ocr-validation', 'confidence-tagging'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'ocr-extract',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
  'QuestionExtractionAgent': {
    name: 'QuestionExtractionAgent',
    description: 'Extracts questions, answers, and explanations into structured formats.',
    capabilities: ['question-extraction', 'explanation-extraction'],
    supportedModels: ['gpt-4o', 'mock-gpt-4'],
    preferredModel: 'gpt-4o',
    promptId: 'ocr-extract',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 3, initialDelayMs: 1000, backoffMultiplier: 2 },
  },
  'DiagramDetectionAgent': {
    name: 'DiagramDetectionAgent',
    description: 'Detects coordinates and text placeholders representing math diagrams.',
    capabilities: ['diagram-coordinates-extraction'],
    supportedModels: ['gpt-4o', 'mock-gpt-4'],
    preferredModel: 'gpt-4o',
    promptId: 'ocr-extract',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 1000, backoffMultiplier: 2 },
  },
  'QuestionClassificationAgent': {
    name: 'QuestionClassificationAgent',
    description: 'Classifies syllabus topic, sub-topic, and curriculum level alignment.',
    capabilities: ['syllabus-tagging'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'topic-classify',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
  'DifficultyAnalyzer': {
    name: 'DifficultyAnalyzer',
    description: 'Analyzes Olympiad difficulty levels based on logic step counts.',
    capabilities: ['difficulty-grading'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'difficulty-analyze',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
  'TopicClassifier': {
    name: 'TopicClassifier',
    description: 'Maps math statements to specific Olympiad categories.',
    capabilities: ['category-tagging'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'topic-classify',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
  'HintGenerator': {
    name: 'HintGenerator',
    description: 'Generates step-by-step Socratic hint guides.',
    capabilities: ['socratic-hint-writing'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'hint-generate',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 3, initialDelayMs: 500, backoffMultiplier: 2 },
  },
  'SolutionGenerator': {
    name: 'SolutionGenerator',
    description: 'Generates rich step-by-step mathematical explanations.',
    capabilities: ['solution-writing'],
    supportedModels: ['gpt-4o', 'mock-gpt-4'],
    preferredModel: 'gpt-4o',
    promptId: 'ocr-extract',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 1000, backoffMultiplier: 2 },
  },
  'MathTutor': {
    name: 'MathTutor',
    description: 'Guides student conversations around formulas and arithmetic.',
    capabilities: ['socratic-tutoring'],
    supportedModels: ['gpt-4o', 'mock-gpt-4'],
    preferredModel: 'gpt-4o',
    promptId: 'hint-generate',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
  'MathCoach': {
    name: 'MathCoach',
    description: 'Provides encouragement, growth-mindset highlights, and milestone feedback.',
    capabilities: ['motivational-coaching'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'hint-generate',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
  'DiscussionAgent': {
    name: 'DiscussionAgent',
    description: 'Answers peer questions in study lobbies.',
    capabilities: ['lobby-moderation'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'hint-generate',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
  'WeaknessAnalyzer': {
    name: 'WeaknessAnalyzer',
    description: 'Analyzes student attempt history to pinpoint weak sub-concepts.',
    capabilities: ['weakness-pattern-analysis'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'topic-classify',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 1000, backoffMultiplier: 2 },
  },
  'LearningAdvisor': {
    name: 'LearningAdvisor',
    description: 'Generates syllabus recommendations.',
    capabilities: ['syllabus-recommender'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'difficulty-analyze',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
  'QuestionGenerator': {
    name: 'QuestionGenerator',
    description: 'Generates brand new math problems based on difficulty rules.',
    capabilities: ['question-generation'],
    supportedModels: ['gpt-4o', 'mock-gpt-4'],
    preferredModel: 'gpt-4o',
    promptId: 'ocr-extract',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 3, initialDelayMs: 1000, backoffMultiplier: 2 },
  },
  'QuestionReviewer': {
    name: 'QuestionReviewer',
    description: 'Verifies readability, difficulty levels, and syllabus parameters.',
    capabilities: ['peer-review'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'difficulty-analyze',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
  'KnowledgeGraphBuilder': {
    name: 'KnowledgeGraphBuilder',
    description: 'Chains concepts together (e.g. factors lead to primes).',
    capabilities: ['graph-indexing'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'topic-classify',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 1000, backoffMultiplier: 2 },
  },
  'ParentReportGenerator': {
    name: 'ParentReportGenerator',
    description: 'Translates math performance stats into simple parent updates.',
    capabilities: ['parent-reporting'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'topic-classify',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
  'ProgressSummaryAgent': {
    name: 'ProgressSummaryAgent',
    description: 'Compiles level milestones and streak metrics.',
    capabilities: ['analytics-aggregation'],
    supportedModels: ['gpt-4o-mini', 'mock-gpt-4'],
    preferredModel: 'gpt-4o-mini',
    promptId: 'difficulty-analyze',
    promptVersion: 'v1',
    retryStrategy: { maxAttempts: 2, initialDelayMs: 500, backoffMultiplier: 1.5 },
  },
};

export class AgentRegistry {
  static getAgent(name: string): AgentConfig {
    const config = agentsDB[name];
    if (!config) {
      throw new Error(`Agent with name "${name}" not found in registry.`);
    }
    return config;
  }

  static listAgents(): AgentConfig[] {
    return Object.values(agentsDB);
  }
}
