// src/application/ai-governance/services/SafetyGuardrailService.ts
import { governanceConfig } from '../config/governanceConfig';
import { Logger } from '@/infra/logger';

/**
 * SafetyGuardrailService protects against prompt injections, jailbreaks, data leakage, and unsafe outputs.
 */
export class SafetyGuardrailService {
  private readonly logger = new Logger('SafetyGuardrailService');

  /**
   * Scan input variables for prompt injection, jailbreak attempts, or leakage.
   * Returns validation result.
   */
  validateInput(variables: Record<string, string>): { isSafe: boolean; reason?: string } {
    const keywords = governanceConfig.safetyKeywords;

    for (const [key, val] of Object.entries(variables)) {
      const lowerVal = String(val).toLowerCase();

      const matchedKeyword = keywords.find((kw) => lowerVal.includes(kw));
      if (matchedKeyword) {
        this.logger.warn('Safety guardrail matched injection signature in inputs', { key, matchedKeyword });
        return {
          isSafe: false,
          reason: `Security constraint violated: matched injection pattern "${matchedKeyword}" in variable "${key}".`,
        };
      }
    }

    return { isSafe: true };
  }

  /**
   * Scan output generated by the LLM for leakages or unsafe text.
   */
  validateOutput(content: string): { isSafe: boolean; reason?: string } {
    const lowerContent = content.toLowerCase();

    // Check for leakages (e.g. system prompts leaked in conversation response)
    const leakageTriggers = [
      'you are a mathematics olympiad',
      'system template',
      'system prompt',
      'expectedoutputschema',
    ];

    const matchedTrigger = leakageTriggers.find((t) => lowerContent.includes(t));
    if (matchedTrigger) {
      this.logger.warn('Safety guardrail matched leakage signature in output content', { matchedTrigger });
      return {
        isSafe: false,
        reason: 'Security leak detected: system prompt parameters found in completions response.',
      };
    }

    return { isSafe: true };
  }
}
export const defaultSafetyGuardrailService = new SafetyGuardrailService();
