// src/infrastructure/monitoring/lipMetrics.ts
/**
 * Prometheus-style counters for the Learning Intelligence Platform.
 *
 * This is a lightweight in-process implementation that exposes metrics
 * via a simple HTTP endpoint. In production you would use the `prom-client`
 * npm package and register these counters there instead.
 */

interface Counter {
  name: string;
  help: string;
  value: number;
}

const counters: Map<string, Counter> = new Map();

function createCounter(name: string, help: string): Counter {
  const counter: Counter = { name, help, value: 0 };
  counters.set(name, counter);
  return counter;
}

// ─── LIP counters ────────────────────────────────────────────────────────────
export const lipEventsIngested = createCounter(
  'lip_events_ingested_total',
  'Total number of learning events ingested by the LIP',
);

export const lipEventsErrored = createCounter(
  'lip_events_errored_total',
  'Total number of learning events that failed to ingest',
);

export const lipPipelineRuns = createCounter(
  'lip_pipeline_runs_total',
  'Total number of analytics pipeline runs',
);

export const lipPipelineErrors = createCounter(
  'lip_pipeline_errors_total',
  'Total number of failed analytics pipeline runs',
);

export const lipInsightsGenerated = createCounter(
  'lip_insights_generated_total',
  'Total number of insights generated by the LIP',
);

// ─── Helpers ─────────────────────────────────────────────────────────────────
export function incrementCounter(counter: Counter, amount = 1): void {
  counter.value += amount;
}

/**
 * Render all counters as a Prometheus text exposition format string.
 * Mount this on GET /metrics in your Express app.
 */
export function renderMetrics(): string {
  const lines: string[] = [];
  for (const counter of counters.values()) {
    lines.push(`# HELP ${counter.name} ${counter.help}`);
    lines.push(`# TYPE ${counter.name} counter`);
    lines.push(`${counter.name} ${counter.value}`);
  }
  return lines.join('\n') + '\n';
}
